/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedTaskTrackerRouteImport } from './routes/_protected/task-tracker'
import { Route as ProtectedScoreTaskRouteImport } from './routes/_protected/score-task'
import { Route as ProtectedReviewerRouteImport } from './routes/_protected/reviewer'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'

const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/_public/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTaskTrackerRoute = ProtectedTaskTrackerRouteImport.update({
  id: '/_protected/task-tracker',
  path: '/task-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedScoreTaskRoute = ProtectedScoreTaskRouteImport.update({
  id: '/_protected/score-task',
  path: '/score-task',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedReviewerRoute = ProtectedReviewerRouteImport.update({
  id: '/_protected/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/_protected/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof ProtectedHomeRoute
  '/reviewer': typeof ProtectedReviewerRoute
  '/score-task': typeof ProtectedScoreTaskRoute
  '/task-tracker': typeof ProtectedTaskTrackerRoute
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof ProtectedHomeRoute
  '/reviewer': typeof ProtectedReviewerRoute
  '/score-task': typeof ProtectedScoreTaskRoute
  '/task-tracker': typeof ProtectedTaskTrackerRoute
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/reviewer': typeof ProtectedReviewerRoute
  '/_protected/score-task': typeof ProtectedScoreTaskRoute
  '/_protected/task-tracker': typeof ProtectedTaskTrackerRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/reviewer'
    | '/score-task'
    | '/task-tracker'
    | '/login'
    | '/sign-up'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/reviewer'
    | '/score-task'
    | '/task-tracker'
    | '/login'
    | '/sign-up'
    | '/'
  id:
    | '__root__'
    | '/_protected/home'
    | '/_protected/reviewer'
    | '/_protected/score-task'
    | '/_protected/task-tracker'
    | '/_public/login'
    | '/_public/sign-up'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedReviewerRoute: typeof ProtectedReviewerRoute
  ProtectedScoreTaskRoute: typeof ProtectedScoreTaskRoute
  ProtectedTaskTrackerRoute: typeof ProtectedTaskTrackerRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/task-tracker': {
      id: '/_protected/task-tracker'
      path: '/task-tracker'
      fullPath: '/task-tracker'
      preLoaderRoute: typeof ProtectedTaskTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/score-task': {
      id: '/_protected/score-task'
      path: '/score-task'
      fullPath: '/score-task'
      preLoaderRoute: typeof ProtectedScoreTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/reviewer': {
      id: '/_protected/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ProtectedReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedReviewerRoute: ProtectedReviewerRoute,
  ProtectedScoreTaskRoute: ProtectedScoreTaskRoute,
  ProtectedTaskTrackerRoute: ProtectedTaskTrackerRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
