/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicLandingRouteImport } from './routes/_public/landing'
import { Route as ProtectedTaskTrackerRouteImport } from './routes/_protected/task-tracker'
import { Route as ProtectedScoreTaskRouteImport } from './routes/_protected/score-task'
import { Route as ProtectedReviewerRouteImport } from './routes/_protected/reviewer'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedSuperAdminUsersRouteImport } from './routes/_protected/super-admin/users'
import { Route as ProtectedSuperAdminTrafficRouteImport } from './routes/_protected/super-admin/traffic'
import { Route as ProtectedSuperAdminSecurityRouteImport } from './routes/_protected/super-admin/security'
import { Route as ProtectedSuperAdminScoresRouteImport } from './routes/_protected/super-admin/scores'
import { Route as ProtectedSuperAdminMonitoringRouteImport } from './routes/_protected/super-admin/monitoring'
import { Route as ProtectedSuperAdminDatabaseRouteImport } from './routes/_protected/super-admin/database'
import { Route as ProtectedSuperAdminDashboardRouteImport } from './routes/_protected/super-admin/dashboard'
import { Route as ProtectedSuperAdminAuditLogsRouteImport } from './routes/_protected/super-admin/audit-logs'

const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/_public/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLandingRoute = PublicLandingRouteImport.update({
  id: '/_public/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTaskTrackerRoute = ProtectedTaskTrackerRouteImport.update({
  id: '/_protected/task-tracker',
  path: '/task-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedScoreTaskRoute = ProtectedScoreTaskRouteImport.update({
  id: '/_protected/score-task',
  path: '/score-task',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedReviewerRoute = ProtectedReviewerRouteImport.update({
  id: '/_protected/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/_protected/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSuperAdminUsersRoute =
  ProtectedSuperAdminUsersRouteImport.update({
    id: '/_protected/super-admin/users',
    path: '/super-admin/users',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSuperAdminTrafficRoute =
  ProtectedSuperAdminTrafficRouteImport.update({
    id: '/_protected/super-admin/traffic',
    path: '/super-admin/traffic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSuperAdminSecurityRoute =
  ProtectedSuperAdminSecurityRouteImport.update({
    id: '/_protected/super-admin/security',
    path: '/super-admin/security',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSuperAdminScoresRoute =
  ProtectedSuperAdminScoresRouteImport.update({
    id: '/_protected/super-admin/scores',
    path: '/super-admin/scores',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSuperAdminMonitoringRoute =
  ProtectedSuperAdminMonitoringRouteImport.update({
    id: '/_protected/super-admin/monitoring',
    path: '/super-admin/monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSuperAdminDatabaseRoute =
  ProtectedSuperAdminDatabaseRouteImport.update({
    id: '/_protected/super-admin/database',
    path: '/super-admin/database',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSuperAdminDashboardRoute =
  ProtectedSuperAdminDashboardRouteImport.update({
    id: '/_protected/super-admin/dashboard',
    path: '/super-admin/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSuperAdminAuditLogsRoute =
  ProtectedSuperAdminAuditLogsRouteImport.update({
    id: '/_protected/super-admin/audit-logs',
    path: '/super-admin/audit-logs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof ProtectedHomeRoute
  '/reviewer': typeof ProtectedReviewerRoute
  '/score-task': typeof ProtectedScoreTaskRoute
  '/task-tracker': typeof ProtectedTaskTrackerRoute
  '/landing': typeof PublicLandingRoute
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
  '/': typeof ProtectedIndexRoute
  '/super-admin/audit-logs': typeof ProtectedSuperAdminAuditLogsRoute
  '/super-admin/dashboard': typeof ProtectedSuperAdminDashboardRoute
  '/super-admin/database': typeof ProtectedSuperAdminDatabaseRoute
  '/super-admin/monitoring': typeof ProtectedSuperAdminMonitoringRoute
  '/super-admin/scores': typeof ProtectedSuperAdminScoresRoute
  '/super-admin/security': typeof ProtectedSuperAdminSecurityRoute
  '/super-admin/traffic': typeof ProtectedSuperAdminTrafficRoute
  '/super-admin/users': typeof ProtectedSuperAdminUsersRoute
}
export interface FileRoutesByTo {
  '/home': typeof ProtectedHomeRoute
  '/reviewer': typeof ProtectedReviewerRoute
  '/score-task': typeof ProtectedScoreTaskRoute
  '/task-tracker': typeof ProtectedTaskTrackerRoute
  '/landing': typeof PublicLandingRoute
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
  '/': typeof ProtectedIndexRoute
  '/super-admin/audit-logs': typeof ProtectedSuperAdminAuditLogsRoute
  '/super-admin/dashboard': typeof ProtectedSuperAdminDashboardRoute
  '/super-admin/database': typeof ProtectedSuperAdminDatabaseRoute
  '/super-admin/monitoring': typeof ProtectedSuperAdminMonitoringRoute
  '/super-admin/scores': typeof ProtectedSuperAdminScoresRoute
  '/super-admin/security': typeof ProtectedSuperAdminSecurityRoute
  '/super-admin/traffic': typeof ProtectedSuperAdminTrafficRoute
  '/super-admin/users': typeof ProtectedSuperAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/reviewer': typeof ProtectedReviewerRoute
  '/_protected/score-task': typeof ProtectedScoreTaskRoute
  '/_protected/task-tracker': typeof ProtectedTaskTrackerRoute
  '/_public/landing': typeof PublicLandingRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/super-admin/audit-logs': typeof ProtectedSuperAdminAuditLogsRoute
  '/_protected/super-admin/dashboard': typeof ProtectedSuperAdminDashboardRoute
  '/_protected/super-admin/database': typeof ProtectedSuperAdminDatabaseRoute
  '/_protected/super-admin/monitoring': typeof ProtectedSuperAdminMonitoringRoute
  '/_protected/super-admin/scores': typeof ProtectedSuperAdminScoresRoute
  '/_protected/super-admin/security': typeof ProtectedSuperAdminSecurityRoute
  '/_protected/super-admin/traffic': typeof ProtectedSuperAdminTrafficRoute
  '/_protected/super-admin/users': typeof ProtectedSuperAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/reviewer'
    | '/score-task'
    | '/task-tracker'
    | '/landing'
    | '/login'
    | '/sign-up'
    | '/'
    | '/super-admin/audit-logs'
    | '/super-admin/dashboard'
    | '/super-admin/database'
    | '/super-admin/monitoring'
    | '/super-admin/scores'
    | '/super-admin/security'
    | '/super-admin/traffic'
    | '/super-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/reviewer'
    | '/score-task'
    | '/task-tracker'
    | '/landing'
    | '/login'
    | '/sign-up'
    | '/'
    | '/super-admin/audit-logs'
    | '/super-admin/dashboard'
    | '/super-admin/database'
    | '/super-admin/monitoring'
    | '/super-admin/scores'
    | '/super-admin/security'
    | '/super-admin/traffic'
    | '/super-admin/users'
  id:
    | '__root__'
    | '/_protected/home'
    | '/_protected/reviewer'
    | '/_protected/score-task'
    | '/_protected/task-tracker'
    | '/_public/landing'
    | '/_public/login'
    | '/_public/sign-up'
    | '/_protected/'
    | '/_protected/super-admin/audit-logs'
    | '/_protected/super-admin/dashboard'
    | '/_protected/super-admin/database'
    | '/_protected/super-admin/monitoring'
    | '/_protected/super-admin/scores'
    | '/_protected/super-admin/security'
    | '/_protected/super-admin/traffic'
    | '/_protected/super-admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedReviewerRoute: typeof ProtectedReviewerRoute
  ProtectedScoreTaskRoute: typeof ProtectedScoreTaskRoute
  ProtectedTaskTrackerRoute: typeof ProtectedTaskTrackerRoute
  PublicLandingRoute: typeof PublicLandingRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSuperAdminAuditLogsRoute: typeof ProtectedSuperAdminAuditLogsRoute
  ProtectedSuperAdminDashboardRoute: typeof ProtectedSuperAdminDashboardRoute
  ProtectedSuperAdminDatabaseRoute: typeof ProtectedSuperAdminDatabaseRoute
  ProtectedSuperAdminMonitoringRoute: typeof ProtectedSuperAdminMonitoringRoute
  ProtectedSuperAdminScoresRoute: typeof ProtectedSuperAdminScoresRoute
  ProtectedSuperAdminSecurityRoute: typeof ProtectedSuperAdminSecurityRoute
  ProtectedSuperAdminTrafficRoute: typeof ProtectedSuperAdminTrafficRoute
  ProtectedSuperAdminUsersRoute: typeof ProtectedSuperAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/landing': {
      id: '/_public/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof PublicLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/task-tracker': {
      id: '/_protected/task-tracker'
      path: '/task-tracker'
      fullPath: '/task-tracker'
      preLoaderRoute: typeof ProtectedTaskTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/score-task': {
      id: '/_protected/score-task'
      path: '/score-task'
      fullPath: '/score-task'
      preLoaderRoute: typeof ProtectedScoreTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/reviewer': {
      id: '/_protected/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ProtectedReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/users': {
      id: '/_protected/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof ProtectedSuperAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/traffic': {
      id: '/_protected/super-admin/traffic'
      path: '/super-admin/traffic'
      fullPath: '/super-admin/traffic'
      preLoaderRoute: typeof ProtectedSuperAdminTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/security': {
      id: '/_protected/super-admin/security'
      path: '/super-admin/security'
      fullPath: '/super-admin/security'
      preLoaderRoute: typeof ProtectedSuperAdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/scores': {
      id: '/_protected/super-admin/scores'
      path: '/super-admin/scores'
      fullPath: '/super-admin/scores'
      preLoaderRoute: typeof ProtectedSuperAdminScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/monitoring': {
      id: '/_protected/super-admin/monitoring'
      path: '/super-admin/monitoring'
      fullPath: '/super-admin/monitoring'
      preLoaderRoute: typeof ProtectedSuperAdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/database': {
      id: '/_protected/super-admin/database'
      path: '/super-admin/database'
      fullPath: '/super-admin/database'
      preLoaderRoute: typeof ProtectedSuperAdminDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/dashboard': {
      id: '/_protected/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof ProtectedSuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin/audit-logs': {
      id: '/_protected/super-admin/audit-logs'
      path: '/super-admin/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof ProtectedSuperAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedReviewerRoute: ProtectedReviewerRoute,
  ProtectedScoreTaskRoute: ProtectedScoreTaskRoute,
  ProtectedTaskTrackerRoute: ProtectedTaskTrackerRoute,
  PublicLandingRoute: PublicLandingRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSuperAdminAuditLogsRoute: ProtectedSuperAdminAuditLogsRoute,
  ProtectedSuperAdminDashboardRoute: ProtectedSuperAdminDashboardRoute,
  ProtectedSuperAdminDatabaseRoute: ProtectedSuperAdminDatabaseRoute,
  ProtectedSuperAdminMonitoringRoute: ProtectedSuperAdminMonitoringRoute,
  ProtectedSuperAdminScoresRoute: ProtectedSuperAdminScoresRoute,
  ProtectedSuperAdminSecurityRoute: ProtectedSuperAdminSecurityRoute,
  ProtectedSuperAdminTrafficRoute: ProtectedSuperAdminTrafficRoute,
  ProtectedSuperAdminUsersRoute: ProtectedSuperAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
